function scrollToSection(sectionId){const section=document.getElementById(sectionId);if(section){const navbarHeight=document.querySelector('.navbar').offsetHeight;const sectionTop=section.getBoundingClientRect().top+window.pageYOffset;window.scrollTo({top:sectionTop-navbarHeight,behavior:'smooth'});const navbarCollapse=document.getElementById('navbarNav');if(navbarCollapse&&navbarCollapse.classList.contains('show')&&typeof bootstrap!=='undefined'&&bootstrap.Collapse){const bsCollapse=new bootstrap.Collapse(navbarCollapse,{toggle:!1});bsCollapse.hide()}}}
var audio=new Audio("./assets/sounds/bird.mp3");document.querySelector('#logo').addEventListener('mouseenter',function(e){audio.play()});let backToTopBtn=document.getElementById("backToTopBtn");window.onscroll=function(){scrollFunction()};function scrollFunction(){if(document.body.scrollTop>20||document.documentElement.scrollTop>20){backToTopBtn.style.display="block"}else{backToTopBtn.style.display="none"}}
function topFunction(){window.scrollTo({top:0,behavior:'smooth'})}
window.topFunction=topFunction;document.addEventListener('DOMContentLoaded',()=>{const imageModals=document.querySelectorAll('.modal');document.querySelectorAll('.navbar-nav .nav-link').forEach(anchor=>{anchor.addEventListener('click',function(e){e.preventDefault();const sectionId=this.getAttribute('href').substring(1);scrollToSection(sectionId)})});function closeNavbarOnLinkClick(){const navLinks=document.querySelectorAll('.navbar-nav .nav-link');const navbarCollapse=document.getElementById('navbarNav');if(navbarCollapse&&typeof bootstrap!=='undefined'&&bootstrap.Collapse){const bsCollapse=new bootstrap.Collapse(navbarCollapse,{toggle:!1});navLinks.forEach(link=>{link.addEventListener('click',()=>{if(navbarCollapse.classList.contains('show')){bsCollapse.hide()}})})}}
document.addEventListener('DOMContentLoaded',closeNavbarOnLinkClick);imageModals.forEach(imageModal=>{imageModal.addEventListener('show.bs.modal',event=>{const opener=event.relatedTarget;const productId=opener.getAttribute('data-product-id');let imageTitle='';let imageSrc=opener.getAttribute('data-bs-image-src');let imageDescription='';if(productId){const product=productData.find(p=>p.id===productId);if(product){imageTitle=product.title;imageDescription=product.description;imageSrc=product.imageSrc}else{console.error(`Product data not found for ID: ${productId}`);imageTitle='Détails de l\'image (Données manquantes)'}}else{imageTitle=opener.getAttribute('data-bs-title')||'Nos Créations';imageDescription=opener.getAttribute('data-bs-description')||''}
const modalImage=imageModal.querySelector('#modalImage');if(modalImage){modalImage.src=imageSrc}
const modalTitle=imageModal.querySelector('.modal-title');if(modalTitle){modalTitle.textContent=imageTitle}
const modalDescription=imageModal.querySelector('#modalDescription');if(modalDescription){modalDescription.textContent=imageDescription}})});if(typeof productData!=='undefined'){productData.forEach(product=>{const imageElement=document.querySelector(`img[data-product-id="${product.id}"]`);if(imageElement){imageElement.src=product.imageSrc;imageElement.alt=product.title;const card=imageElement.closest('.card');const titleElement=card?card.querySelector('.card-body .card-text'):null;const priceElement=card?card.querySelector('.product-price'):null;if(titleElement){titleElement.textContent=product.title}
if(priceElement){priceElement.textContent=product.price}}})}})
